language: php

php:
    - 7.0
    - 5.6
    - 5.5
    - 5.4

before_script:
    - composer self-update
    - composer install --prefer-source
    - wget https://scrutinizer-ci.com/ocular.phar

script:
    - php vendor/atoum/atoum/scripts/coverage.php --format xml --output clover.xml

after_script:
    - php ocular.phar code-coverage:upload --format=php-clover clover.xml
